[project]
name = "facttest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "factorio-draftsman>=3.1.0",
    "factoriocalc>=0.3.0",
    "pyperclip>=1.9.0",
    "rich>=14.1.0",
]
